### ISSUE TITLE
Extensão do dominio

### ISSUE THREAD

**Issue by rsantosdev** [Dev-ES/cademeucarro#3]
Olá pessoALL,

Vou começar a centralizar algumas discussões aqui no GH, assim o pessoal pode ir se familiarizando com o projeto sem precisar reler a thread no slack.

Primeira pergunta: Qual extensão de dominio usaremos?

* [ ] .io
* [ ] .com
* [ ] ~~.com.br~~ (não disponivel)

Sugiram as extensões que desejam, bem como um local que seja mais barato para compra do mesmo.

**Comment by jvrmaia** [comment]
`.com`

**Comment by jvrmaia** [comment]
`.io`

**Comment by jvrmaia** [comment]
coloquem um :+1: na opção que preferirem p/ facilitar a contagem

**Comment by ruanmartinelli** [comment]
`cademeucarro.org`?

**Comment by jvrmaia** [comment]
Acho que já pode fechar. quem vai comprar? Onde vai hospedar o DNS?

**Comment by rsantosdev** [comment]
Vamos fechar no `.com` mesmo então.
Comprar acho que vamos ver quem oferece mais barato, eu geralmente quase sempre pego no GoDaddy.

**Comment by jvrmaia** [comment]
Não gosto de GoDaddy mas ok se for o mais barato

**Comment by ruanmartinelli** [comment]
Ajudo na vaquinha se precisar :v: Cadê um PicPay pra transferir?

**Comment by rsantosdev** [comment]
@jvrmaia  Com o problema com o Godaddy ?!
@ruanmartinelli tinah pensado exatamente isso, vou jogar no slack para conversamos melhor.

**Comment by jvrmaia** [comment]
fixed http://api.cademeucarro.org/swagger/
