### ISSUE TITLE
Monorepo ou Multirepo

### ISSUE THREAD

**Issue by jvrmaia** [Dev-ES/cademeucarro#5]
Acham melhor desenvolver as APPs aqui dividias em pastas ou preferem criar um reposiório para cada e linkar aqui?

**Comment by jvrmaia** [comment]
Monorepo

**Comment by jvrmaia** [comment]
Multirepo

**Comment by jvrmaia** [comment]
Votem ai :+1:

**Comment by rsantosdev** [comment]
Ficou decidido Multirepo mesmo
